README.md
=> grammatical fixes

kong/common/kong-auth-pep-common.lua, kong/plugins/gluu-oauth-pep/handler.lua, kong/plugins/gluu-uma-pep/handler.lua, t/lib/kong_utils.lua, t/specs/gluu-oauth-pep/test_spec.lua
=> fix priority bug and add X-Authenticated-Scope header

kong/plugins/gluu-oauth-pep/access.lua, t/specs/gluu-oauth-pep/oxd-model5.lua, t/specs/gluu-oauth-pep/oxd-model6.lua, t/specs/gluu-oauth-pep/test_spec.lua
=> JWT vulnerabilities - test cases and code to avoid

kong/common/kong-common.lua, kong/plugins/gluu-openid-connect/access.lua, kong/plugins/gluu-openid-connect/schema.lua, kong/plugins/gluu-uma-pep/access.lua, t/specs/gluu-oauth-pep/test_spec.lua, t/specs/gluu-openid-connect/oxd-model1.lua, t/specs/gluu-openid-connect/oxd-model2.lua, t/specs/gluu-openid-connect/oxd-model3.lua, t/specs/gluu-openid-connect/oxd-model4.lua, t/specs/gluu-openid-connect/test_spec.lua
=> Userinfo claim and id token push claim fixes

kong/common/kong-common.lua, kong/plugins/gluu-uma-pep/access.lua, t/specs/gluu-openid-connect/oxd-model3.lua, t/specs/gluu-openid-connect/oxd-model4.lua
PR with fixes
https://github.com/GluuFederation/gluu-gateway/issues/312: 
https://github.com/GluuFederation/gluu-gateway/issues/314:
https://github.com/GluuFederation/gluu-gateway/issues/315:
=> ticket issue and claim token format issue

kong/plugins/gluu-opa-pep/access.lua, kong/plugins/gluu-opa-pep/handler.lua, kong/plugins/gluu-opa-pep/schema.lua, t/lib/kong_utils.lua, t/specs/gluu-opa-pep/mock-oauth-auth/handler.lua, t/specs/gluu-opa-pep/mock-oauth-auth/schema.lua, t/specs/gluu-opa-pep/policy.rego, t/specs/gluu-opa-pep/test_spec.lua
=> add gluu-opa-pep plugin and test cases

kong/plugins/gluu-metrics/access.lua, kong/plugins/gluu-metrics/handler.lua, kong/plugins/gluu-metrics/schema.lua, t/Dockerfile, t/specs/gluu-metrics/mock-oauth-auth/handler.lua, t/specs/gluu-metrics/mock-oauth-auth/schema.lua, t/specs/gluu-metrics/test_spec.lua
Updated the gluu-metrics plugin to check gluu lincese server IP in 24hr(configurable)
@altexy needs one suggestion, how to get IP of the current docker container? we need it in the test case.
=> Update ip restrictriction plugin with gluu license server ip

kong/plugins/gluu-openid-connect/access.lua
=> Redirect loop

setup/setup-gluu-gateway.py
Allow only root user to execute the setup-gluu-gateway.py script.
=> Checked and validate root user

kong/common/kong-common.lua, kong/common/path-wildcard-tree.lua, kong/plugins/gluu-metrics/metrics.lua, kong/plugins/gluu-oauth-pep/access.lua, kong/plugins/gluu-oauth-pep/schema.lua, kong/plugins/gluu-opa-pep/access.lua, kong/plugins/gluu-openid-connect/access.lua, kong/plugins/gluu-openid-connect/schema.lua, kong/plugins/gluu-uma-pep/access.lua, kong/plugins/gluu-uma-pep/schema.lua, konga/assets/js/app/plugins/modals/path-possibilities-modal.html, konga/assets/js/app/plugins/modals/show-acr-expression-json-modal.html, konga/assets/js/app/plugins/oauth-plugin-controller.js, konga/assets/js/app/plugins/oauth-plugin.html, konga/assets/js/app/plugins/openid-plugin-controller.js, konga/assets/js/app/plugins/openid-plugin.html, konga/assets/js/app/plugins/uma-plugin-controller.js, konga/assets/js/app/plugins/uma-plugin.html, setup/setup-gluu-gateway.py, setup/templates/kong.conf, t/specs/gluu-oauth-auth/test_spec.lua, t/specs/gluu-oauth-pep/test_spec.lua, t/specs/gluu-openid-connect/oxd-model5.lua, t/specs/gluu-openid-connect/oxd-model6.lua, t/specs/gluu-openid-connect/test_spec.lua, t/specs/gluu-uma-auth/test_spec.lua
=> url based acrs and unescaped whitespace in URI

kong/plugins/gluu-openid-connect/access.lua, t/specs/gluu-openid-connect/oxd-model7.lua, t/specs/gluu-openid-connect/test_spec.lua
=> Fix requested acrs nil

kong/plugins/gluu-openid-connect/access.lua, t/specs/gluu-openid-connect/test_spec.lua
=> Unset method path tree

kong/plugins/gluu-openid-connect/access.lua
=> Added max_age in authorization url using OXD command

kong/common/json-cache.lua, kong/common/kong-common.lua, kong/plugins/gluu-metrics/api.lua, kong/plugins/gluu-metrics/metrics.lua, kong/plugins/gluu-metrics/schema.lua, kong/plugins/gluu-oauth-auth/schema.lua, kong/plugins/gluu-oauth-pep/schema.lua, kong/plugins/gluu-opa-pep/schema.lua, kong/plugins/gluu-openid-connect/access.lua, kong/plugins/gluu-openid-connect/schema.lua, kong/plugins/gluu-uma-auth/schema.lua, kong/plugins/gluu-uma-pep/schema.lua, t/lib/kong_utils.lua, t/specs/gluu-metrics/test_spec.lua, t/specs/gluu-oauth-auth/test_spec.lua, t/specs/gluu-oauth-pep/test_spec.lua, t/specs/gluu-opa-pep/test_spec.lua, t/specs/gluu-openid-connect/test_spec.lua, t/specs/gluu-uma-auth/test_spec.lua, t/specs/gluu-uma-pep/test_spec.lua
=> Convert all plugins to Kong 1.3

kong/common/kong-common.lua, kong/plugins/gluu-metrics/metrics.lua, kong/plugins/gluu-oauth-auth/schema.lua, kong/plugins/gluu-uma-auth/schema.lua, t/specs/gluu-metrics/mock-oauth-auth/handler.lua, t/specs/gluu-metrics/mock-uma-auth/handler.lua, t/specs/gluu-oauth-auth/test_spec.lua, t/specs/gluu-opa-pep/mock-oauth-auth/handler.lua
=> Make Kong consumer <-> Oauth2 client mapping optional

t/run-image.sh
close  #396
I did build an image locally with a name and run all tests using new script, works fine.
=> add ability to run test suite against any docker image

lib/gluu/kong-common.lua
=> fix refresh_pending logic

lib/gluu/kong-common.lua, lib/kong/plugins/gluu-oauth-auth/schema.lua, lib/kong/plugins/gluu-openid-connect/schema.lua, lib/kong/plugins/gluu-uma-auth/schema.lua, lib/kong/plugins/gluu-uma-pep/access.lua, lib/kong/plugins/gluu-uma-pep/schema.lua, t/specs/gluu-openid-connect/oxd-model3.lua, t/specs/gluu-openid-connect/test_spec.lua
=> uma custom pushed claims

lib/kong/plugins/gluu-metrics/metrics.lua
=> avoid error for no-service metrics

Dockerfile, t/lib/kong_utils.lua
=> bump Kong to 1.5.0

lib/gluu/path-wildcard-tree.lua, t/specs/gluu-oauth-pep/oxd-model3.lua, t/specs/gluu-oauth-pep/test_spec.lua, t/specs/path-wildcard-tree/test_spec.lua
=> prefix match multiple wildcard

lib/kong/plugins/gluu-openid-connect/access.lua, t/specs/gluu-openid-connect/test_spec.lua
=> Add missed oidc headers for non protected page

t/lib/kong_utils.lua, t/lib/test_utils.lua, t/specs/gluu-openid-connect/test_spec.lua
=> Test of injecting resty session config

lib/gluu/openid_connect_session_data.lua, lib/kong/plugins/gluu-openid-connect/access.lua, t/lib/kong_utils.lua, t/specs/gluu-openid-connect/oxd-model9.lua, t/specs/gluu-openid-connect/test_spec.lua
=> Full gluu-openid-connect refactoring

.gitmodules
=> feat: Updated submodules #419

lib/gluu/kong-common.lua, lib/gluu/path-wildcard-tree.lua, lib/kong/plugins/gluu-oauth-pep/access.lua, t/specs/gluu-oauth-pep/oxd-model10.lua, t/specs/gluu-oauth-pep/test_spec.lua, t/specs/path-wildcard-tree/path-wildcard-tree-tester.lua, t/specs/path-wildcard-tree/test.nginx, t/specs/path-wildcard-tree/test_spec.lua
=> gluu-oauth-pep spontaneous scopes

lib/gluu/kong-common.lua, t/specs/gluu-oauth-pep/test_spec.lua
=> Ensure zero or one ?? pattern in a path

lib/gluu/kong-common.lua, lib/kong/plugins/gluu-openid-connect/access.lua, lib/kong/plugins/gluu-openid-connect/schema.lua, t/specs/gluu-openid-connect/test_spec.lua
=> Restore original auth params

lib/kong/plugins/gluu-openid-connect/access.lua, lib/kong/plugins/gluu-uma-pep/access.lua, t/specs/gluu-openid-connect/test_spec.lua, t/specs/gluu-uma-pep/test_spec.lua
=> Hide session cookie from upstream

Dockerfile, lib/gluu/kong-common.lua, lib/kong/plugins/gluu-uma-pep/access.lua, t/lib/kong_utils.lua
=> Add Lua expressions cache

lib/kong/plugins/gluu-oauth-pep/schema.lua
close https://github.com/GluuFederation/gluu-gateway/issues/447
Test cases passed.
=> fix: update name in schema lua #447

.gitmodules
=> feat: Updated json-login-lua modules
